In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df_categorical = pd.read_csv('df_training_combined_categorical.csv', parse_dates=['date_recorded'], na_values=['NaN'])
df_categorical.head()

,date_recorded,funder,installer,wpt_name,basin,subvillage,region,lga,ward,public_meeting,...,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group,id,target
0,2011-03-14,Roman,Roman,none,Lake Nyasa,Mnyusi B,Iringa,Ludewa,Mundindi,True,...,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe,69572,functional
1,2013-03-06,Grumeti,GRUMETI,Zahanati,Lake Victoria,Nyamara,Mara,Serengeti,Natta,NaN,...,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,8776,functional
2,2013-02-25,Lottery Club,World vision,Kwa Mahundi,Pangani,Majengo,Manyara,Simanjiro,Ngorika,True,...,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe,34310,functional
3,2013-01-28,Unicef,UNICEF,Zahanati Ya Nanyumbu,Ruvuma / Southern Coast,Mahakamani,Mtwara,Nanyumbu,Nanyumbu,True,...,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe,67743,non functional
4,2011-07-13,Action In A,Artisan,Shuleni,Lake Victoria,Kyanyamisa,Kagera,Karagwe,Nyakasimbi,True,...,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe,19728,functional

In [3]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [4]:
date_recorded = df_categorical.pop('date_recorded')
date_recorded.head()

0   2011-03-14
1   2013-03-06
2   2013-02-25
3   2013-01-28
4   2011-07-13
Name: date_recorded, dtype: datetime64[ns]

In [5]:
df_categorical.head()

         funder     installer              wpt_name                    basin  subvillage   region        lga        ward public_meeting              recorded_by scheme_management                  scheme_name permit extraction_type extraction_type_group extraction_type_class management management_group         payment payment_type water_quality quality_group      quantity quantity_group                source           source_type source_class              waterpoint_type waterpoint_type_group     id          target
0         Roman         Roman                  none               Lake Nyasa    Mnyusi B   Iringa     Ludewa    Mundindi           True  GeoData Consultants Ltd               VWC                        Roman  False         gravity               gravity               gravity        vwc       user-group    pay annually     annually          soft          good        enough         enough                spring                spring  groundwater           communal standpipe    communal standpipe  69572      functional
1       Grumeti       GRUMETI              Zahanati            Lake Victoria     Nyamara     Mara  Serengeti       Natta            NaN  GeoData Consultants Ltd             Other                          NaN   True         gravity               gravity               gravity        wug       user-group       never pay    never pay          soft          good  insufficient   insufficient  rainwater harvesting  rainwater harvesting      surface           communal standpipe    communal standpipe   8776      functional
2  Lottery Club  World vision           Kwa Mahundi                  Pangani     Majengo  Manyara  Simanjiro     Ngorika           True  GeoData Consultants Ltd               VWC  Nyumba ya mungu pipe scheme   True         gravity               gravity               gravity        vwc       user-group  pay per bucket   per bucket          soft          good        enough         enough                   dam                   dam      surface  communal standpipe multiple    communal standpipe  34310      functional
3        Unicef        UNICEF  Zahanati Ya Nanyumbu  Ruvuma / Southern Coast  Mahakamani   Mtwara   Nanyumbu    Nanyumbu           True  GeoData Consultants Ltd               VWC                          NaN   True     submersible           submersible           submersible        vwc       user-group       never pay    never pay          soft          good           dry            dry           machine dbh              borehole  groundwater  communal standpipe multiple    communal standpipe  67743  non functional
4   Action In A       Artisan               Shuleni            Lake Victoria  Kyanyamisa   Kagera    Karagwe  Nyakasimbi           True  GeoData Consultants Ltd               NaN                          NaN   True         gravity               gravity               gravity      other            other       never pay    never pay          soft          good      seasonal       seasonal  rainwater harvesting  rainwater harvesting      surface           communal standpipe    communal standpipe  19728      functional

In [6]:
df_categorical.shape

(59400, 31)

In [7]:
df_categorical['funder'] = df_categorical['funder'].fillna(df_categorical['funder'].mode()[0])
df_categorical['subvillage'] = df_categorical['subvillage'].fillna(df_categorical['subvillage'].mode()[0])
df_categorical['public_meeting'] = df_categorical['public_meeting'].fillna(df_categorical['public_meeting'].mode()[0])
df_categorical['permit'].fillna(df_categorical['permit'].describe().top, inplace=True)

In [8]:
df_categorical.isna().sum()

funder                       0
installer                 3655
wpt_name                     0
basin                        0
subvillage                   0
region                       0
lga                          0
ward                         0
public_meeting               0
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                       0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
id                           0
target                       0
dtype: int64

In [9]:
funder_cleaned = []

for row in df_categorical['funder']:
    if row == 'Government Of Tanzania':
        funder_cleaned.append('Tanzania')
    else:
        funder_cleaned.append('Other')
        
df_categorical['funder_cleaned'] = funder_cleaned

In [10]:
installer_cleaned = []

for row in df_categorical['installer']:
    if row == 'DWE':
        installer_cleaned.append('DWE')
    else:
        installer_cleaned.append('Other')
        
df_categorical['installer_cleaned'] = installer_cleaned

In [11]:
scheme_management_cleaned = []

for row in df_categorical['scheme_management']:
    if row == 'VWC':
        scheme_management_cleaned.append('VWC')
    else:
        scheme_management_cleaned.append('Other')
        
df_categorical['scheme_management_cleaned'] = scheme_management_cleaned

In [12]:
extraction_type_cleaned = []

for row in df_categorical['extraction_type']:
    if row == 'gravity':
        extraction_type_cleaned.append('gravity')
    else:
        extraction_type_cleaned.append('other')
    
df_categorical['extraction_type_cleaned'] = extraction_type_cleaned

In [13]:
management_cleaned = []

for row in df_categorical['management']:
    if row == 'vwc':
        management_cleaned.append('vwc')
    else:
        management_cleaned.append('other')
    
df_categorical['management_cleaned'] = management_cleaned

In [14]:
management_group_cleaned = []

for row in df_categorical['management_group']:
    if row == 'user-group':
        management_group_cleaned.append('user-group')
    else:
        management_group_cleaned.append('other')
        
df_categorical['management_group_cleaned'] = management_group_cleaned

In [15]:
payment_cleaned = []

for row in df_categorical['payment']:
    if row == 'never pay':
        payment_cleaned.append('never pay')
    else:
        payment_cleaned.append('other')
        
df_categorical['payment_cleaned'] = payment_cleaned

In [16]:
water_quality_cleaned = []

for row in df_categorical['water_quality']:
    if row == 'soft':
        water_quality_cleaned.append('soft')
    else:
        water_quality_cleaned.append('other')
        
df_categorical['water_quality_cleaned'] = water_quality_cleaned

In [17]:
quality_group_cleaned = []

for row in df_categorical['quality_group']:
    if row == 'good':
        quality_group_cleaned.append('good')
    else:
        quality_group_cleaned.append('other')
        
df_categorical['quality_group_cleaned'] = quality_group_cleaned

In [18]:
quantity_cleaned = []

for row in df_categorical['quantity']:
    if row == 'enough':
        quantity_cleaned.append('enough')
    else:
        quantity_cleaned.append('other')
        
df_categorical['quantity_cleaned'] = quantity_cleaned

In [19]:
source_cleaned = []

for row in df_categorical['source']:
    if row == 'spring':
        source_cleaned.append('spring')
    elif row == 'shallow well':
        source_cleaned.append('shallow well')
    elif row == 'machine dbh':
        source_cleaned.append('machine dbh')
    else:
        source_cleaned.append('other')
        
df_categorical['source_cleaned'] = source_cleaned

In [20]:
source_class_cleaned = []

for row in df_categorical['source_class']:
    if row == 'groundwater':
        source_class_cleaned.append('groundwater')
    else:
        source_class_cleaned.append('surface')
        
df_categorical['source_class_cleaned'] = source_class_cleaned

In [21]:
waterpoint_type_cleaned = []

for row in df_categorical['waterpoint_type']:
    if ((row == 'communal standpipe') or (row == 'communal standpipe multiple')):
        waterpoint_type_cleaned.append('standpipe')
    elif row == 'hand pump':
        waterpoint_type_cleaned.append('handpump')
    else:
        waterpoint_type_cleaned.append('other')
        
df_categorical['waterpoint_type_cleaned'] = waterpoint_type_cleaned

In [22]:
df_categorical.head()

         funder     installer              wpt_name                    basin  subvillage   region        lga        ward  public_meeting              recorded_by scheme_management                  scheme_name  permit extraction_type extraction_type_group extraction_type_class management management_group         payment payment_type water_quality quality_group      quantity quantity_group                source           source_type source_class              waterpoint_type waterpoint_type_group     id          target funder_cleaned installer_cleaned scheme_management_cleaned extraction_type_cleaned management_cleaned management_group_cleaned payment_cleaned water_quality_cleaned quality_group_cleaned quantity_cleaned source_cleaned source_class_cleaned waterpoint_type_cleaned
0         Roman         Roman                  none               Lake Nyasa    Mnyusi B   Iringa     Ludewa    Mundindi            True  GeoData Consultants Ltd               VWC                        Roman   False         gravity               gravity               gravity        vwc       user-group    pay annually     annually          soft          good        enough         enough                spring                spring  groundwater           communal standpipe    communal standpipe  69572      functional          Other             Other                       VWC                 gravity                vwc               user-group           other                  soft                  good           enough         spring          groundwater               standpipe
1       Grumeti       GRUMETI              Zahanati            Lake Victoria     Nyamara     Mara  Serengeti       Natta            True  GeoData Consultants Ltd             Other                          NaN    True         gravity               gravity               gravity        wug       user-group       never pay    never pay          soft          good  insufficient   insufficient  rainwater harvesting  rainwater harvesting      surface           communal standpipe    communal standpipe   8776      functional          Other             Other                     Other                 gravity              other               user-group       never pay                  soft                  good            other          other              surface               standpipe
2  Lottery Club  World vision           Kwa Mahundi                  Pangani     Majengo  Manyara  Simanjiro     Ngorika            True  GeoData Consultants Ltd               VWC  Nyumba ya mungu pipe scheme    True         gravity               gravity               gravity        vwc       user-group  pay per bucket   per bucket          soft          good        enough         enough                   dam                   dam      surface  communal standpipe multiple    communal standpipe  34310      functional          Other             Other                       VWC                 gravity                vwc               user-group           other                  soft                  good           enough          other              surface               standpipe
3        Unicef        UNICEF  Zahanati Ya Nanyumbu  Ruvuma / Southern Coast  Mahakamani   Mtwara   Nanyumbu    Nanyumbu            True  GeoData Consultants Ltd               VWC                          NaN    True     submersible           submersible           submersible        vwc       user-group       never pay    never pay          soft          good           dry            dry           machine dbh              borehole  groundwater  communal standpipe multiple    communal standpipe  67743  non functional          Other             Other                       VWC                   other                vwc               user-group       never pay                  soft                  good            other    machine dbh          groundwater               standpipe
4   Action In A       Artisan               Shuleni            Lake Victoria  Kyanyamisa   Kagera    Karagwe  Nyakasimbi            True  GeoData Consultants Ltd               NaN                          NaN    True         gravity               gravity               gravity      other            other       never pay    never pay          soft          good      seasonal       seasonal  rainwater harvesting  rainwater harvesting      surface           communal standpipe    communal standpipe  19728      functional          Other             Other                     Other                 gravity              other                    other       never pay                  soft                  good            other          other              surface               standpipe

In [23]:
drop_list = ['wpt_name', 'basin', 'subvillage', 'funder',
             'installer', 'scheme_management', 'permit', 'public_meeting',
             'lga', 'ward', 'recorded_by', 'region', 'scheme_name', 'extraction_type',
             'extraction_type_group', 'extraction_type_class', 'management',
             'management_group','payment', 'payment_type', 'water_quality',
             'quality_group', 'quantity', 'quantity_group','source', 'source_class',
             'source_type', 'waterpoint_type', 'waterpoint_type_group']

df_categorical.drop(drop_list, axis=1, inplace=True)
df_categorical.head()

      id          target funder_cleaned installer_cleaned scheme_management_cleaned extraction_type_cleaned management_cleaned management_group_cleaned payment_cleaned water_quality_cleaned quality_group_cleaned quantity_cleaned source_cleaned source_class_cleaned waterpoint_type_cleaned
0  69572      functional          Other             Other                       VWC                 gravity                vwc               user-group           other                  soft                  good           enough         spring          groundwater               standpipe
1   8776      functional          Other             Other                     Other                 gravity              other               user-group       never pay                  soft                  good            other          other              surface               standpipe
2  34310      functional          Other             Other                       VWC                 gravity                vwc               user-group           other                  soft                  good           enough          other              surface               standpipe
3  67743  non functional          Other             Other                       VWC                   other                vwc               user-group       never pay                  soft                  good            other    machine dbh          groundwater               standpipe
4  19728      functional          Other             Other                     Other                 gravity              other                    other       never pay                  soft                  good            other          other              surface               standpipe

In [24]:
df_categorical.dtypes

id                            int64
target                       object
funder_cleaned               object
installer_cleaned            object
scheme_management_cleaned    object
extraction_type_cleaned      object
management_cleaned           object
management_group_cleaned     object
payment_cleaned              object
water_quality_cleaned        object
quality_group_cleaned        object
quantity_cleaned             object
source_cleaned               object
source_class_cleaned         object
waterpoint_type_cleaned      object
dtype: object

In [25]:
df_categorical.isna().sum()

id                           0
target                       0
funder_cleaned               0
installer_cleaned            0
scheme_management_cleaned    0
extraction_type_cleaned      0
management_cleaned           0
management_group_cleaned     0
payment_cleaned              0
water_quality_cleaned        0
quality_group_cleaned        0
quantity_cleaned             0
source_cleaned               0
source_class_cleaned         0
waterpoint_type_cleaned      0
dtype: int64

In [26]:
df_categorical['target'].value_counts(normalize=True)

functional                 0.543081
non functional             0.384242
functional needs repair    0.072677
Name: target, dtype: float64

In [27]:
target_cleaned = []

for row in df_categorical['target']:
    if row == 'functional':
        target_cleaned.append('functional')
    elif row == 'funtional needs repair':
        target_cleaned.append('functional')
    else: 
        target_cleaned.append('non functional')

df_categorical['target_cleaned'] = target_cleaned

In [28]:
df_categorical['target_cleaned'].value_counts(normalize=True)

functional        0.543081
non functional    0.456919
Name: target_cleaned, dtype: float64

In [29]:
df_categorical.to_csv('categorical_only_cleaned.csv', index=False)

In [30]:
target = df_categorical.pop('target')
target_cleaned = df_categorical.pop('target_cleaned')

In [31]:
print("Original Features:\n", list(df_categorical.columns), "\n")
df_categorical_dummies = pd.get_dummies(df_categorical)
print("Features after get_dummies: \n", list(df_categorical_dummies.columns))

Original Features:
 ['id', 'funder_cleaned', 'installer_cleaned', 'scheme_management_cleaned', 'extraction_type_cleaned', 'management_cleaned', 'management_group_cleaned', 'payment_cleaned', 'water_quality_cleaned', 'quality_group_cleaned', 'quantity_cleaned', 'source_cleaned', 'source_class_cleaned', 'waterpoint_type_cleaned']

Features after get_dummies:
 ['id', 'funder_cleaned_Other', 'funder_cleaned_Tanzania', 'installer_cleaned_DWE', 'installer_cleaned_Other', 'scheme_management_cleaned_Other', 'scheme_management_cleaned_VWC', 'extraction_type_cleaned_gravity', 'extraction_type_cleaned_other', 'management_cleaned_other', 'management_cleaned_vwc', 'management_group_cleaned_other', 'management_group_cleaned_user-group', 'payment_cleaned_never pay', 'payment_cleaned_other', 'water_quality_cleaned_other', 'water_quality_cleaned_soft', 'quality_group_cleaned_good', 'quality_group_cleaned_other', 'quantity_cleaned_enough', 'quantity_cleaned_other', 'source_cleaned_machine dbh', 'source_cleaned_other', 'source_cleaned_shallow well', 'source_cleaned_spring', 'source_class_cleaned_groundwater', 'source_class_cleaned_surface', 'waterpoint_type_cleaned_handpump', 'waterpoint_type_cleaned_other', 'waterpoint_type_cleaned_standpipe']

In [32]:
df_categorical_dummies.head()

      id  funder_cleaned_Other  funder_cleaned_Tanzania  installer_cleaned_DWE  installer_cleaned_Other  scheme_management_cleaned_Other  scheme_management_cleaned_VWC  extraction_type_cleaned_gravity  extraction_type_cleaned_other  management_cleaned_other  management_cleaned_vwc  management_group_cleaned_other  management_group_cleaned_user-group  payment_cleaned_never pay  payment_cleaned_other  water_quality_cleaned_other  water_quality_cleaned_soft  quality_group_cleaned_good  quality_group_cleaned_other  quantity_cleaned_enough  quantity_cleaned_other  source_cleaned_machine dbh  source_cleaned_other  source_cleaned_shallow well  source_cleaned_spring  source_class_cleaned_groundwater  source_class_cleaned_surface  waterpoint_type_cleaned_handpump  waterpoint_type_cleaned_other  waterpoint_type_cleaned_standpipe
0  69572                     1                        0                      0                        1                                0                              1                                1                              0                         0                       1                               0                                    1                          0                      1                            0                           1                           1                            0                        1                       0                           0                     0                            0                      1                                 1                             0                                 0                              0                                  1
1   8776                     1                        0                      0                        1                                1                              0                                1                              0                         1                       0                               0                                    1                          1                      0                            0                           1                           1                            0                        0                       1                           0                     1                            0                      0                                 0                             1                                 0                              0                                  1
2  34310                     1                        0                      0                        1                                0                              1                                1                              0                         0                       1                               0                                    1                          0                      1                            0                           1                           1                            0                        1                       0                           0                     1                            0                      0                                 0                             1                                 0                              0                                  1
3  67743                     1                        0                      0                        1                                0                              1                                0                              1                         0                       1                               0                                    1                          1                      0                            0                           1                           1                            0                        0                       1                           1                     0                            0                      0                                 1                             0                                 0                              0                                  1
4  19728                     1                        0                      0                        1                                1                              0                                1                              0                         1                       0                               1                                    0                          1                      0                            0                           1                           1                            0                        0                       1                           0                     1                            0                      0                                 0                             1                                 0                              0                                  1

In [33]:
df_categorical_dummies.shape

(59400, 30)

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X = df_categorical_dummies.drop('id', axis=1)
y = target_cleaned

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

lr = LogisticRegression(C=100).fit(X_train, y_train)

print("Training score: {:.2f}".format(lr.score(X_train, y_train)))
print()
print("Testing score: {:.2f}".format(lr.score(X_test, y_test)))

/Users/sammylee/miniconda3/envs/datascience/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

Training score: 0.67

Testing score: 0.67

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X = df_categorical_dummies.drop('id', axis=1)
y = target_cleaned

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

rf = RandomForestClassifier(n_estimators=100, min_samples_leaf=3).fit(X_train, y_train)

print("Training score: {:.2f}".format(rf.score(X_train, y_train)))
print()
print("Testing score: {:.2f}".format(rf.score(X_test, y_test)))

Training score: 0.72

Testing score: 0.71

In [36]:
df_categorical.head()

      id funder_cleaned installer_cleaned scheme_management_cleaned extraction_type_cleaned management_cleaned management_group_cleaned payment_cleaned water_quality_cleaned quality_group_cleaned quantity_cleaned source_cleaned source_class_cleaned waterpoint_type_cleaned
0  69572          Other             Other                       VWC                 gravity                vwc               user-group           other                  soft                  good           enough         spring          groundwater               standpipe
1   8776          Other             Other                     Other                 gravity              other               user-group       never pay                  soft                  good            other          other              surface               standpipe
2  34310          Other             Other                       VWC                 gravity                vwc               user-group           other                  soft                  good           enough          other              surface               standpipe
3  67743          Other             Other                       VWC                   other                vwc               user-group       never pay                  soft                  good            other    machine dbh          groundwater               standpipe
4  19728          Other             Other                     Other                 gravity              other                    other       never pay                  soft                  good            other          other              surface               standpipe

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import category_encoders as ce

X = df_categorical.drop('id', axis=1)
y = target_cleaned

encoder = ce.OneHotEncoder()
X_encoded = encoder.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, random_state=42)

lr = LogisticRegression(C=100).fit(X_train, y_train)

print("Training score: {:.2f}".format(lr.score(X_train, y_train)))
print()
print("Testing score: {:.2f}".format(lr.score(X_test, y_test)))

/Users/sammylee/miniconda3/envs/datascience/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

Training score: 0.67

Testing score: 0.67

In [38]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import category_encoders as ce

X = df_categorical.drop('id', axis=1)
y = target_cleaned

encoder = ce.OneHotEncoder()
X_encoded = encoder.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, random_state=42)

rf = RandomForestClassifier(n_estimators=100, min_samples_leaf=3).fit(X_train, y_train)

print("Training score: {:.2f}".format(rf.score(X_train, y_train)))
print()
print("Testing score: {:.2f}".format(rf.score(X_test, y_test)))

Training score: 0.72

Testing score: 0.71

In [39]:
df_categorical.head()

      id funder_cleaned installer_cleaned scheme_management_cleaned extraction_type_cleaned management_cleaned management_group_cleaned payment_cleaned water_quality_cleaned quality_group_cleaned quantity_cleaned source_cleaned source_class_cleaned waterpoint_type_cleaned
0  69572          Other             Other                       VWC                 gravity                vwc               user-group           other                  soft                  good           enough         spring          groundwater               standpipe
1   8776          Other             Other                     Other                 gravity              other               user-group       never pay                  soft                  good            other          other              surface               standpipe
2  34310          Other             Other                       VWC                 gravity                vwc               user-group           other                  soft                  good           enough          other              surface               standpipe
3  67743          Other             Other                       VWC                   other                vwc               user-group       never pay                  soft                  good            other    machine dbh          groundwater               standpipe
4  19728          Other             Other                     Other                 gravity              other                    other       never pay                  soft                  good            other          other              surface               standpipe